In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.12.1+cpu


In [19]:
# Tensors
# scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())
print(scalar.shape)

# vector
vector = torch.tensor([3,4,5])
print(vector)
print(vector.ndim)
print(vector.shape)
print(vector.dtype)
print(vector.device)
# similar stuff goes with matrix and tensors...

tensor(7)
0
7
torch.Size([])
tensor([3, 4, 5])
1
torch.Size([3])
torch.int64
cpu


In [3]:
# Random Tensors
tensor = torch.rand(3,4,4)*4
print(tensor)
print(tensor.ndim)
print(tensor.shape)
# all the usual numpy stuff...

tensor([[[1.4488, 0.6310, 1.2504, 2.2734],
         [1.2621, 3.0745, 1.4183, 3.8322],
         [3.2819, 0.4648, 1.9234, 1.0731],
         [1.7269, 0.9089, 0.4647, 0.0935]],

        [[3.6399, 0.8722, 1.4714, 1.6529],
         [3.1085, 2.1317, 3.8673, 1.3354],
         [0.5155, 3.8487, 1.4487, 1.8827],
         [0.9389, 3.1538, 2.9751, 2.3491]],

        [[0.4031, 3.0362, 1.8524, 0.8056],
         [1.5533, 0.1656, 3.9246, 0.1170],
         [3.0585, 3.1896, 3.9534, 0.8748],
         [0.2492, 0.4777, 2.6460, 2.5771]]])
3
torch.Size([3, 4, 4])


In [4]:
img = torch.rand(size=(224, 224, 3)) # sinitializing, ame thing
print(img.shape)
print(img.ndim)
print(img.dtype)
# print(img[0:2][0:2][:5])

torch.Size([224, 224, 3])
3
torch.float32


In [5]:
# other ways of initializing
print(torch.zeros(2,3,2))
print(torch.ones(2,3))
print(torch.zeros_like(torch.arange(0,5))) # make zeros tensor with same shape

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([0, 0, 0, 0, 0])


In [6]:
# range
torch.arange(0,4) # similar to python range()

tensor([0, 1, 2, 3])

In [9]:
# dtype
float16_t = torch.rand((2,4), dtype=torch.float16) # various data types available
# other arguments like device and requires_grad exist

### Major reasons for errors
- Tensor data types
- Tensor shape
- Tensor device

In [20]:
# type conversion
float8_t = float16_t.type(torch.float8_e5m2)
float8_t
# float8_t * float16_t # error

tensor([[0.1094, 0.8750, 0.5000, 0.7500],
        [0.3750, 0.3750, 0.6250, 0.1094]], dtype=torch.float8_e5m2)

In [30]:
# other methods
x = torch.arange(1,10)
torch.max(x), x.max() # either way works

# NOTE: Can't get mean from int, needs float or complex
x.type(torch.float32).mean() # or torch.mean(Tensor)
x.sum(), torch.sum(x)
torch.argmin(x), x.argmin() # argmax, I believe the tensor gets flattened

(tensor(0), tensor(0))